[tool.poetry]
name = "poetry init"
version = "0.1.0"
description = "job_parser"
authors = ["DariaBushueva <bushueva84@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
